# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWSH-KmpzfjgUOFSg0ZSQyXiKxiDPGn-
"""

# using pandas
import pandas as pd
devices={
    'devices':['devices 1' ,'device 2','device 3','device 4'],
    'usage':[7,8,2,18],
    'iot_sensors':[1,2,3,4]
}
df=pd.DataFrame(devices)
df['total_usage']=df['usage']+df['iot_sensors']
print(df)
import matplotlib.pyplot as plt
time=[2,4,6,8]#sec
device_usage_data=[10,20,30,40]
plt.plot(time,device_usage_data,marker='h')
plt.xlabel('time(sec)')
plt.ylabel('device usage')
plt.title("device usage vs time")
plt.show()
plt.plot(time,iot_sensors,marker="h")
plt.xlabel('time(sec)')
plt.ylabel('iot sensors')
plt.title("iot sensors vs time")
plt.show()
plt.plot(device_usage_data,iot_sensors,marker='h')
plt.xlabel('device usage')
plt.ylabel('iot sensors')
plt.title("device usage vs iot sensors")
plt.show()